---
title: "tidy invasives"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## setup

```{r setup}
# import packages
library(tidyverse)
library(janitor)
library(readr)

# custom functions
skimmer <- function(layer, n) {
  sapply(layer, function(x) {
    uniq <- unique(x)
    if (length(uniq) < n)
      uniq_values = sort(uniq)
    else
      length(uniq)
  })
}

# import data
treatments <- read_tsv("NRTSy/RPT_TREATMENT_DETAILS_VW_DATA_VIEW.tsv") |>
  clean_names()

infestations <- readxl::read_xls("invasive_plant_infestations.xls") |>
  clean_names()

```

```{r explore}
skimmer(treatments, 50)

multis <- treatments |>
  count(treatment_date, infestation_area_id, scientific_name, sort  = TRUE) |>
  filter(n != 1) |>
  head(3) |>
  select(-4)

semi_join(treatments, multis) |>
  view()

unique(treatments$active_adjuvant) 

treatments |>
  mutate(active_adjuvant = strsplit(active_adjuvant, '|'),
         active_ingredient = strsplit(active_ingredient, '|')) |>
  unnest(active_adjuvant, active_ingredient)
  
  # select(active_adjuvant) |>
  separate_wider_delim(active_adjuvant, '|', names = c('adjuvant1','adjuvant2','adjuvant3'), too_few = 'align_start') |>
  
```


```{r explore infestations}
infestations |>
  filter(park_name == 'Alfred B. Maclay Gardens State Park') |>
  select(dominant_species, species_observed) |>
    # count(dominant_species, sort = TRUE)
  separate_longer_delim(species_observed, '/') |>
  count(species_observed, sort = TRUE)
```

